/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as TvRouteImport } from './routes/tv'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as GenreGenreIdRouteImport } from './routes/genre.$genreId'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ApiPublicPayheroCallbackRouteImport } from './routes/api/public/payhero-callback'
import { Route as ApiPublicHooksRenewSubscriptionsRouteImport } from './routes/api/public/hooks/renew-subscriptions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreGenreIdRoute = GenreGenreIdRouteImport.update({
  id: '/genre/$genreId',
  path: '/genre/$genreId',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPayheroCallbackRoute =
  ApiPublicPayheroCallbackRouteImport.update({
    id: '/api/public/payhero-callback',
    path: '/api/public/payhero-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRenewSubscriptionsRoute =
  ApiPublicHooksRenewSubscriptionsRouteImport.update({
    id: '/api/public/hooks/renew-subscriptions',
    path: '/api/public/hooks/renew-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/tv': typeof TvRoute
  '/watch': typeof WatchRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/r/$code': typeof RCodeRoute
  '/api/public/payhero-callback': typeof ApiPublicPayheroCallbackRoute
  '/api/public/hooks/renew-subscriptions': typeof ApiPublicHooksRenewSubscriptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/tv': typeof TvRoute
  '/watch': typeof WatchRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/r/$code': typeof RCodeRoute
  '/api/public/payhero-callback': typeof ApiPublicPayheroCallbackRoute
  '/api/public/hooks/renew-subscriptions': typeof ApiPublicHooksRenewSubscriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/tv': typeof TvRoute
  '/watch': typeof WatchRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/r/$code': typeof RCodeRoute
  '/api/public/payhero-callback': typeof ApiPublicPayheroCallbackRoute
  '/api/public/hooks/renew-subscriptions': typeof ApiPublicHooksRenewSubscriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/download'
    | '/movies'
    | '/my-list'
    | '/new'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/subscribe'
    | '/tv'
    | '/watch'
    | '/genre/$genreId'
    | '/r/$code'
    | '/api/public/payhero-callback'
    | '/api/public/hooks/renew-subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/download'
    | '/movies'
    | '/my-list'
    | '/new'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/subscribe'
    | '/tv'
    | '/watch'
    | '/genre/$genreId'
    | '/r/$code'
    | '/api/public/payhero-callback'
    | '/api/public/hooks/renew-subscriptions'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/download'
    | '/movies'
    | '/my-list'
    | '/new'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/subscribe'
    | '/tv'
    | '/watch'
    | '/genre/$genreId'
    | '/r/$code'
    | '/api/public/payhero-callback'
    | '/api/public/hooks/renew-subscriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DownloadRoute: typeof DownloadRoute
  MoviesRoute: typeof MoviesRoute
  MyListRoute: typeof MyListRoute
  NewRoute: typeof NewRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SubscribeRoute: typeof SubscribeRoute
  TvRoute: typeof TvRoute
  WatchRoute: typeof WatchRoute
  GenreGenreIdRoute: typeof GenreGenreIdRoute
  RCodeRoute: typeof RCodeRoute
  ApiPublicPayheroCallbackRoute: typeof ApiPublicPayheroCallbackRoute
  ApiPublicHooksRenewSubscriptionsRoute: typeof ApiPublicHooksRenewSubscriptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$genreId': {
      id: '/genre/$genreId'
      path: '/genre/$genreId'
      fullPath: '/genre/$genreId'
      preLoaderRoute: typeof GenreGenreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payhero-callback': {
      id: '/api/public/payhero-callback'
      path: '/api/public/payhero-callback'
      fullPath: '/api/public/payhero-callback'
      preLoaderRoute: typeof ApiPublicPayheroCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/renew-subscriptions': {
      id: '/api/public/hooks/renew-subscriptions'
      path: '/api/public/hooks/renew-subscriptions'
      fullPath: '/api/public/hooks/renew-subscriptions'
      preLoaderRoute: typeof ApiPublicHooksRenewSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DownloadRoute: DownloadRoute,
  MoviesRoute: MoviesRoute,
  MyListRoute: MyListRoute,
  NewRoute: NewRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SubscribeRoute: SubscribeRoute,
  TvRoute: TvRoute,
  WatchRoute: WatchRoute,
  GenreGenreIdRoute: GenreGenreIdRoute,
  RCodeRoute: RCodeRoute,
  ApiPublicPayheroCallbackRoute: ApiPublicPayheroCallbackRoute,
  ApiPublicHooksRenewSubscriptionsRoute: ApiPublicHooksRenewSubscriptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
